version: '3'

services:
  hardhat:
    build: .
    container_name: nft42-hardhat
    working_dir: /app
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    tty: true